version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx:latest
    container_name: kem_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fontend:/var/www/html
      - ./backend:/var/www/api
    depends_on:
      - vuejs
      - composer_installation
    ports:
      - 80:80
    networks:
      - app

  vuejs:
    image: kem_vuejs
    container_name: kem_vuejs
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    volumes:
      - ./fontend:/var/www/html
    ports:
      - 8080:8080
    depends_on:
      - laravel
    networks:
      - app

  laravel:
    image: kem_php
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
    container_name: kem_php
    ports:
      - 9000:9000
    volumes:
      - ./backend:/var/www/api
    depends_on:
      - mysqlvue
    restart: always
    networks:
      - app

  mysqlvue:
    image: mysql:5.7.22
    container_name: mysqlvue
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/init/tbl_todos.sql:/docker-entrypoint-initdb.d/tbl_todos.sql
    environment: 
      MYSQL_DATABASE: backend
      MYSQL_USER: vuejstodo
      MYSQL_PASSWORD: todo
      MYSQL_ROOT_PASSWORD: todo
    networks:
      - app

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./backend:/app
    command: composer install --ignore-platform-reqs
    networks:
      - app

networks:
  app: